#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

set -x

################################################################################
# Example usage:                                                               #
# ./generate-jni-header com.example.some.Class some/file/path.jni.h            #
################################################################################

JNI_HEADERS_DIRECTORY=$CARLIE_PROJECT_DIRECTORY/jni-headers

JNI_HEADER_CLASS_NAME=$1
JNI_HEADER_FILE_PATH=$2

mkdir -p $JNI_HEADERS_DIRECTORY
$JAVA_HOME/bin/javah -classpath "$($CARLIE_PROJECT_DIRECTORY/gradlew --quiet --system-prop org.gradle.project.buildDir=$CARLIE_PROJECT_DIRECTORY/jni-header-gradle-build printRuntimeClasspath)" -jni -o $JNI_HEADERS_DIRECTORY/$JNI_HEADER_FILE_PATH $JNI_HEADER_CLASS_NAME
