#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

set -x

################################################################################
# Example usage:                                                               #
# ./gradle-compile-c-sources-script /home/project linux-x86_64                 #
################################################################################

PROJECT_DIRECTORY=$1
PLATFORM=$2

# https://stackoverflow.com/a/32981392
# unbuffer -p $PROJECT_DIRECTORY/tools/cross-compile/run-$PLATFORM "/home/project/cmake-run-build"
unbuffer $PROJECT_DIRECTORY/tools/cross-compile/run-$PLATFORM "/home/project/cmake-run-build"
