#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

docker run \
  --rm \
  dockcross/windows-static-x64@sha256:96f9f658692bcadc1135f272188c59efc1dcb93effe82f8af0e98443f61f1a36 \
  > ./dockcross-windows-x64-static
chmod +x ./dockcross-windows-x64-static

docker run \
  --rm \
  dockcross/windows-static-x86@sha256:6bb573265563d877597e2dd434b51dbcf3dadc743f67972120eadcfe98b26c90 \
  > ./dockcross-windows-x86-static
chmod +x ./dockcross-windows-x86-static

docker run \
  --rm \
  dockcross/linux-x64@sha256:12f7f116e9ac7710ffc7516c2da8d07f4bb3847c9dd44c28483feca0935dcc0f \
  > ./dockcross-linux-x64
chmod +x ./dockcross-linux-x64

docker run \
  --rm \
  dockcross/linux-arm64@sha256:3170edb6a3b1f599bda07dad371b92fe30c932d20a01cba5cbcff233e656bc54 \
  > ./dockcross-linux-arm64
chmod +x ./dockcross-linux-arm64
