#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

docker run \
  --rm \
  dockcross/windows-x64@sha256:e7b666fead78738423bda1529a9c0c680477f89b39936b9cc219e35a8ae7fca2 \
  > ./dockcross-windows-x64
chmod +x ./dockcross-windows-x64

docker run \
  --rm \
  dockcross/windows-x86@sha256:c0828396cb79405d3187bf361d16d1b0fff156edbc1ee30922d8251d206888a7 \
  > ./dockcross-windows-x86
chmod +x ./dockcross-windows-x86

docker run \
  --rm \
  dockcross/linux-x64@sha256:12f7f116e9ac7710ffc7516c2da8d07f4bb3847c9dd44c28483feca0935dcc0f \
  > ./dockcross-linux-x64
chmod +x ./dockcross-linux-x64

docker run \
  --rm \
  dockcross/linux-arm64@sha256:3170edb6a3b1f599bda07dad371b92fe30c932d20a01cba5cbcff233e656bc54 \
  > ./dockcross-linux-arm64
chmod +x ./dockcross-linux-arm64
