#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

SCRIPT_DIRECTORY=$(dirname "$0")

$SCRIPT_DIRECTORY/dockcross-windows-x64-static \
  --image "dockcross/windows-static-x64@sha256:96f9f658692bcadc1135f272188c59efc1dcb93effe82f8af0e98443f61f1a36" \
  bash -c "$*"
