#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

./dockcross-windows-x64 \
  --image "dockcross/windows-x64@sha256:e7b666fead78738423bda1529a9c0c680477f89b39936b9cc219e35a8ae7fca2" \
  bash -c "$*"
