#!/usr/bin/env bash

################################################################################
# Copyright 2019-present Jay B. <j@1791.io>                                    #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License");              #
# you may not use this file except in compliance with the License.             #
# You may obtain a copy of the License at                                      #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
################################################################################

SCRIPT_PATH=${BASH_SOURCE[0]}

SCRIPT_DIRECTORY=$(dirname "$SCRIPT_PATH")
SCRIPT_DIRECTORY="$(cd $SCRIPT_DIRECTORY >/dev/null 2>&1 && pwd)"

PROJECT_DIRECTORY=$SCRIPT_DIRECTORY/../..
PROJECT_DIRECTORY="$(cd $PROJECT_DIRECTORY >/dev/null 2>&1 && pwd)"
CONTAINER_PROJECT_DIRECTORY=/home/project

PROJECT_VERSION=$(cat $PROJECT_DIRECTORY/VERSION)

BUILD_TARGET_ARCHITECTURE="x86_64"
BUILD_TARGET_OS="mac"

# PROJECT_NATIVE_SOURCES=$PROJECT_DIRECTORY/src/main/native/carlie
CONTAINER_PROJECT_NATIVE_SOURCES=$CONTAINER_PROJECT_DIRECTORY/src/main/native/carlie

BUILD_JDK_PATH=$PROJECT_DIRECTORY/resources/jdk/$BUILD_TARGET_OS/$BUILD_TARGET_ARCHITECTURE
CONTAINER_BUILD_JDK_PATH=/home/jdk
CONTAINER_BUILD_JAVA_HOME=$CONTAINER_BUILD_JDK_PATH/Contents/Home
CONTAINER_BUILD_JDK_INCLUDE_DIRECTORIES="$CONTAINER_BUILD_JAVA_HOME/include/darwin;$CONTAINER_BUILD_JAVA_HOME/include"

JAVA_HOME=$PROJECT_DIRECTORY/resources/jdk/linux/x86_64
CONTAINER_JAVA_HOME=/home/java-home

BUILD_JVM_NATIVE_PATH=$PROJECT_DIRECTORY/resources/native/$BUILD_TARGET_OS/$BUILD_TARGET_ARCHITECTURE
CONTAINER_BUILD_JVM_NATIVE_PATH=/home/jvm/native
CONTAINER_BUILD_JVM_NATIVE_INCLUDE_DIRECTORY=$CONTAINER_BUILD_JVM_NATIVE_PATH/include
CONTAINER_BUILD_JVM_NATIVE_LIBRARIES_DIRECTORY=$CONTAINER_BUILD_JVM_NATIVE_PATH/lib

CMAKE_BUILD_PATH=$PROJECT_DIRECTORY/cmake-build/$BUILD_TARGET_OS/$BUILD_TARGET_ARCHITECTURE
CONTAINER_CMAKE_BUILD_PATH=/home/cmake-build

JVM_PACKAGE_NATIVE_LIBRARIES=$PROJECT_DIRECTORY/src/main/resources/native-libraries/$BUILD_TARGET_OS/$BUILD_TARGET_ARCHITECTURE
CONTAINER_JVM_PACKAGE_NATIVE_LIBRARIES=/home/jvm/package-native-libraries

docker run \
  --env CARLIE_BUILD_JAVA_HOME=$CONTAINER_BUILD_JAVA_HOME \
  --env CARLIE_BUILD_JDK_INCLUDE_DIRECTORIES=$CONTAINER_BUILD_JDK_INCLUDE_DIRECTORIES \
  --env CARLIE_BUILD_JDK_PATH=$CONTAINER_BUILD_JDK_PATH \
  --env CARLIE_BUILD_JVM_NATIVE_INCLUDE_DIRECTORY=$CONTAINER_BUILD_JVM_NATIVE_INCLUDE_DIRECTORY \
  --env CARLIE_BUILD_JVM_NATIVE_LIBRARIES_DIRECTORY=$CONTAINER_BUILD_JVM_NATIVE_LIBRARIES_DIRECTORY \
  --env CARLIE_BUILD_JVM_NATIVE_PATH=$CONTAINER_BUILD_JVM_NATIVE_PATH \
  --env CARLIE_BUILD_TARGET_ARCHITECTURE=$BUILD_TARGET_ARCHITECTURE \
  --env CARLIE_BUILD_TARGET_OS=$BUILD_TARGET_OS \
  --env CARLIE_CMAKE_BUILD_PATH=$CONTAINER_CMAKE_BUILD_PATH \
  --env CARLIE_JVM_PACKAGE_NATIVE_LIBRARIES=$CONTAINER_JVM_PACKAGE_NATIVE_LIBRARIES \
  --env CARLIE_PROJECT_DIRECTORY=$CONTAINER_PROJECT_DIRECTORY \
  --env CARLIE_PROJECT_NATIVE_SOURCES=$CONTAINER_PROJECT_NATIVE_SOURCES \
  --env CARLIE_PROJECT_VERSION=$PROJECT_VERSION \
  --env CROSS_TRIPLE=x86_64-apple-darwin \
  --env JAVA_HOME=$CONTAINER_JAVA_HOME \
  --interactive \
  --rm \
  --tty \
  --volume $PWD:/workdir \
  --volume $PROJECT_DIRECTORY:$CONTAINER_PROJECT_DIRECTORY \
  --volume $JAVA_HOME:$CONTAINER_JAVA_HOME \
  --volume $BUILD_JDK_PATH:$CONTAINER_BUILD_JDK_PATH \
  --volume $BUILD_JVM_NATIVE_PATH:$CONTAINER_BUILD_JVM_NATIVE_PATH \
  --volume $CMAKE_BUILD_PATH:$CONTAINER_CMAKE_BUILD_PATH \
  --volume $JVM_PACKAGE_NATIVE_LIBRARIES:$CONTAINER_JVM_PACKAGE_NATIVE_LIBRARIES \
  multiarch/crossbuild@sha256:84a53371f554a3b3d321c9d1dfd485b8748ad6f378ab1ebed603fe1ff01f7b4d \
  "$@"
